= JGiven Documentation =

.Living Documentation
[NOTE]
This documentation is written in AsciiDoc. The documentation is partly handwritten and partly generated by JGiven.

:toc: left

toc::[]

== Introduction ==

JGiven is a Behavior-Driven Development (BDD) tool for Java.
It enables you to write _clean_, _readable_, and _modular_ test code and allows you to generate a behavioral documentation
that is readable by non-developers like business analysts and testers.

=== Comparison to other BDD tools for Java ===

There are already quite a lot BDD tools for Java out there, so why should you use JGiven?
Because it combines _developer-friendliness_ with the possibility to generate a documentation that is readable by
 _non-developers_.

JGiven originally was written as a framework for making JUnit tests
more readable and maintainable. Only afterwards, it was discovered that one can also generate a documentation out
of it.

==== JBehave and Cucumber ====
JBehave and Cucumber are both classical BDD tools where scenarios are written in _plain text_.
The advantage of that approach is that non-developers can _write_ scenarios.
However, it has the big disadvantage that it causes a non-negligible maintenance overhead for developers.
In our experience it is very hard to get business experts to write such scenarios, and even if they do the scenarios
must often be revised by developers to match the test infrastructure.
The maintenance overhead can lead to much frustration or even complete abundance of the BDD approach.

==== Concordion and Fitness ====
Concordion and Fitness take a similar but slightly different approach. Test documentation is written in HTML
instead of plain text. The developer the writes test fixtures to bind HTML to Java code.
Similar to JBehave and Cucumber there is an additional maintenance overhead for developers.
There is, however, a larger freedom when writing the documentation as it is not bound to the Given-When-Then
format.

==== Spock, ScalaTest, and LambdaBehave ====
These specification-based test frameworks take a different approach. They are very developer-centric and
are more a replacement for JUnit than BDD tools. Specifications in these frameworks are better structured and
readable than plain JUnit tests, however, the resulting reports are typically not in a form that can be given
and understood by business experts, but rather by developers. In addition, these frameworks have in common that
they require an additional language (except LambdaBehave which requires Java 8).

==== JGiven ====
In JGiven scenarios are written in a developer-friendly language, namely Java
footnote:[There are some languages out there which claim to be even more developer-friendly than Java like Groovy and Scala, for example.
Naturally, JGiven scenarios can also be written in these languages.].
This means that there is nearly no additional overhead in writing JGiven scenarios compared to writing plain JUnit tests.
In fact, after you are used to write scenarios in JGiven you even might not want to get back to plain JUnit tests,
 because of the additional benefits like readability and modularity.

Note, that the fact that developers write their scenarios in Java does *not* prevent business experts from writing
behavioral specifications! They just use other tools for that. A business expert could, for example, write
acceptance criteria in an issue tracker or they could write it in a word processing tool.
In the end a developer will translate these acceptance criteria in JGiven scenarios.
The resulting reports can then be shown, discussed, and revised together with the business experts.


== JGiven Scenarios ==

The following documentation was generated by JGiven.

=== Classes ===

include::allClasses.asciidoc[]
