package com.tngtech.jgiven.exampleprojects.java21.module;

import com.tngtech.jgiven.Stage;
import com.tngtech.jgiven.annotation.Quoted;
import com.tngtech.jgiven.annotation.ScenarioState;

/**
 * A package-private stage class.
 *
 * <p>This is the interesting case for JGiven's instrumentation: because the
 * class is package-private, JGiven's
 * {@link com.tngtech.jgiven.impl.ByteBuddyStageClassCreator} must inject its
 * generated ByteBuddy subclass into the <em>same runtime package</em> as this
 * class, which under JPMS is only permitted when the declaring module has
 * {@code opens}ed the package (see {@code module-info.java}).</p>
 *
 * <p>It also declares its {@code @ScenarioState} fields package-private, which
 * requires reflective access through
 * {@link com.tngtech.jgiven.impl.inject.ValueInjector}.</p>
 */
class PackagePrivateStage extends Stage<PackagePrivateStage> {

    @ScenarioState
    String message;

    @ScenarioState
    String result;

    PackagePrivateStage given_message(@Quoted String message) {
        this.message = message;
        return self();
    }

    PackagePrivateStage when_appending_suffix(String suffix) {
        result = message + suffix;
        return self();
    }
}
