package com.tngtech.jgiven.gradle.internal;

import com.tngtech.jgiven.gradle.JGivenReport;
import com.tngtech.jgiven.report.AbstractReportConfig;
import com.tngtech.jgiven.report.AbstractReportGenerator;
import com.tngtech.jgiven.report.ReportGenerator;
import com.tngtech.jgiven.report.asciidoc.AsciiDocReportConfig;
import com.tngtech.jgiven.report.asciidoc.AsciiDocReportGenerator;
import com.tngtech.jgiven.report.html5.Html5ReportConfig;
import com.tngtech.jgiven.report.text.PlainTextReportConfig;
import com.tngtech.jgiven.report.text.PlainTextReportGenerator;
import groovy.lang.Closure;
import jakarta.annotation.Nullable;
import java.io.File;
import org.gradle.api.NonNullApi;
import org.gradle.api.Task;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.reporting.Report;
import org.gradle.api.tasks.Internal;
import org.gradle.util.internal.ConfigureUtil;

@NonNullApi
public abstract class AbstractJGivenReportImpl implements JGivenReport {

    private File customCssFile;
    private File customJsFile;
    private String title;
    private boolean excludeEmptyScenarios = false;
    private boolean thumbnailsAreShown = true;
    private final String taskPath;
    private final String name;
    private final String relativeEntryPath;

    public AbstractJGivenReportImpl( String name, Task task, String relativeEntryPath ) {
        this.name = name;
        this.taskPath = task.getPath();
        this.relativeEntryPath = relativeEntryPath;
        this.getRequired().convention(false);
    }

    @Override
    public AbstractReportGenerator createGenerator() {
        AbstractReportConfig conf;
        AbstractReportGenerator generator;
        switch( getFormat() ) {
            case ASCIIDOC:
                conf = new AsciiDocReportConfig();
                generator = new AsciiDocReportGenerator();
                break;
            case TEXT:
                conf = new PlainTextReportConfig();
                generator = new PlainTextReportGenerator();
                break;
            case HTML:
            case HTML5:
            default:
                var customConf = new Html5ReportConfig();
                customConf.setShowThumbnails( isThumbnailsAreShown() );
                if (getCustomCssFile() != null) {
                    customConf.setCustomCss( getCustomCssFile() );
                }
                if (getCustomJsFile() != null) {
                    customConf.setCustomJs( getCustomJsFile() );
                }
                conf = customConf;
                generator = ReportGenerator.loadHtml5ReportGenerator();
                break;
        }
        if( getTitle() != null ) {
            conf.setTitle( getTitle() );
        }

        conf.setTargetDir( getOutputLocation().getAsFile().get() );
        conf.setExcludeEmptyScenarios( isExcludeEmptyScenarios() );
        generator.setConfig( conf );
        return generator;
    }

    @Internal
    public abstract ReportGenerator.Format getFormat();

    @Override @Nullable public File getCustomCssFile() {
        return customCssFile;
    }

    @Override public void setCustomCssFile( File customCssFile ) {
        this.customCssFile = customCssFile;
    }

    @Override @Nullable public File getCustomJsFile() {
        return customJsFile;
    }

    @Override public void setCustomJsFile( File customJsFile ) {
        this.customJsFile = customJsFile;
    }

    @Override @Nullable public String getTitle() {
        return title;
    }

    @Override public void setTitle( String title ) {
        this.title = title;
    }

    @Override public boolean isExcludeEmptyScenarios() {
        return excludeEmptyScenarios;
    }

    @Override public void setExcludeEmptyScenarios( boolean excludeEmptyScenarios ) {
        this.excludeEmptyScenarios = excludeEmptyScenarios;
    }

    @Override public boolean isThumbnailsAreShown() {
        return thumbnailsAreShown;
    }

    @Override public void setThumbnailsAreShown( boolean thumbnailsAreShown ) {
        this.thumbnailsAreShown = thumbnailsAreShown;
    }

    @Override
    public File getEntryPoint() {
        return new File(this.getOutputLocation().getAsFile().getOrNull(), this.relativeEntryPath);
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getDisplayName() {
        return "Report generated by task '" + taskPath + "' (" + name + ")";
    }

    @Override
    public abstract Property<Boolean> getRequired();

    @Override
    public abstract DirectoryProperty getOutputLocation();

    @Override
    @Deprecated
    public void setDestination(File file) {
        throw new UnsupportedOperationException("Use outputLocation instead");
    }

    @Override
    public Report.OutputType getOutputType() {
        return Report.OutputType.DIRECTORY;
    }

    @Override
    public Report configure(Closure configure) {
        return ConfigureUtil.configureSelf(configure, this);
    }

}
