buildscript {
    repositories {
        if (project.hasProperty("staging")) {
            maven { url = uri("https://oss.sonatype.org/content/repositories/staging/") }
        }
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        val version: String by project
        classpath("com.tngtech.jgiven:jgiven-gradle-plugin:$version")
    }
}

plugins {
    java
}

apply(plugin = "com.tngtech.jgiven.gradle-plugin")

// Treat this project as a JPMS named module: the module-info.java in
// src/test/java makes the test source set a named module, and Gradle
// --patch-module's the compiled test classes into it. This exercises
// JGiven's deep reflection (stage subclassing, @ScenarioState field
// access) on the real module-system code path rather than the
// unnamed-module / classpath fallback. Gradle infers the module path
// automatically because src/test/java/module-info.java exists
// (java.modularity.inferModulePath defaults to true).

val version: String by project

tasks.compileJava {
    sourceCompatibility = JavaVersion.VERSION_26.toString()
    targetCompatibility = JavaVersion.VERSION_26.toString()
    options.compilerArgs.add("-parameters")
    options.encoding = "UTF-8"
}

tasks.compileTestJava {
    sourceCompatibility = JavaVersion.VERSION_26.toString()
    targetCompatibility = JavaVersion.VERSION_26.toString()
    options.compilerArgs.add("-parameters")
    options.encoding = "UTF-8"
}

repositories {
    if (project.hasProperty("staging")) {
        maven { url = uri("https://oss.sonatype.org/content/repositories/staging/") }
    }
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation("com.tngtech.jgiven:jgiven-junit6:$version")
    testImplementation("org.junit.jupiter:junit-jupiter-api:6.1.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:6.1.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:6.1.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:6.1.0")
    testImplementation("org.slf4j:slf4j-jdk14:2.0.18")
}

tasks.test {
    useJUnitPlatform()
    // PlainTextReporter touches jansi's internal CLibrary on stdout detection,
    // which is not accessible under JPMS (jansi does not export that package).
    // The HTML report generated by `jgivenTestReport` below is unaffected.
    systemProperty("jgiven.report.text", "false")
    finalizedBy("jgivenTestReport")
}
