== Android

JGiven can be used to test Android applications.
For unit-tests, which are not running on an Android device or emulator, you can just use `jgiven-junit`.
You don't have to do any special test setup to get that working.

=== Testing on an Device or Emulator (EXPERIMENTAL)

If you want to execute your tests on an Android device or emulator, for example when you want to use the _Espresso_
test framework, then you need some additional setup.

CAUTION: This feature is still in an experimental status. This means that it is not tested very well yet and that
the implementation might be changed in a backwards-incompatible way in future versions of JGiven.


==== JGiven Android Dependency
First of all you need an additional project dependency to the `jgiven-android` module:

[source,maven,subs="verbatim,attributes"]
----
<dependency>
   <groupId>com.tngtech.jgiven</groupId>
   <artifactId>jgiven-android</artifactId>
   <version>{version}</version>
   <scope>test</scope>
</dependency>
----

or in Gradle with:

[source,gradle,subs="verbatim,attributes"]
----
dependencies {
    androidTestCompile("com.tngtech.jgiven:jgiven-android:{version}")
}
----

==== Enable additional Permissions

JGiven writes JSON files during the execution of the tests to the external storage of the device or emulator.
Thus you have to enable the permission `WRITE_EXTERNAL_STORAGE` when executing the tests.
You can do that by creating a file `src/debug/AndroidManifest.xml` than enables that permission:

[source,XML]
----
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="the.package.of.my.app">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

</manifest>
----

==== AndroidJGivenTestRule

In your test classes you have to add the following additional JUnit rule:

[source, Java]
----
@Rule
public AndroidJGivenTestRule androidJGivenTestRule = new AndroidJGivenTestRule(this.getScenario());
----

In addition it is useful to expose the `ActivityTestRule` to Stages by
using the `@ScenarioState` annotation:

[source, Java]
----
@Rule
@ScenarioState
public ActivityTestRule<MainActivity> activityTestRule = new ActivityTestRule<>(MainActivity.class);
----

==== Pull JGiven JSON files from device

When the test execution has finished, you need to pull the JGiven JSON files from the device to the local drive.
You can do that using the `adb` tool. The following Gradle task does the job:

[source,gradle]
----
def targetDir = 'build/reports/jgiven/json'
def adb = android.getAdbExe().toString()
def reportsDir = '/storage/emulated/0/Download/jgiven-reports'

task cleanJGivenReports(type: Delete) {
  delete targetDir
}

task pullJGivenReports(type: Exec, dependsOn: cleanJGivenReports) {
    doFirst {
        if (!file(targetDir).mkdirs()) {
            println("Cannot create dir "+targetDir)
        }
    }

    commandLine adb, 'pull', reportsDir, targetDir

    doLast {
        println("Pulled "+reportsDir+" to "+targetDir);
    }
}
----

==== Generate HTML Report

Given the local JSON files, you can generate the HTML report as described in <<_report_generation>>

==== Taking Screen Shots in Espresso Tests

It is very useful to take screen shots during your tests and add them to the JGiven documentation.
When using the _Espresso_ framework, you can use the following piece of code to take
a screenshot of an activity and turn it into a `byte` array:

[source, Java]
----
public class ScreenshotUtil {
    public static byte[] takeScreenshot(Activity activity) {
        View view = activity.getWindow().getDecorView().getRootView();
        view.setDrawingCacheEnabled(true);
        Bitmap bitmap = Bitmap.createBitmap(view.getDrawingCache());
        view.setDrawingCacheEnabled(false);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, baos);
        return baos.toByteArray();
    }
}
----

This byte array can then be added to a step of a JGiven report as usual:

[source, Java]
----
public class MyStage {
    @ScenarioState
    CurrentStep currentStep;

    @ScenarioState
    ActivityTestRule<MainActivity> activityTestRule;

    public Steps clicking_the_Click_Me_button() {
        onView(withId(R.id.clickMeButton)).perform(click());
        takeScreenshot();
        return this;
    }

    @Hidden
    public void takeScreenshot() {
        currentStep.addAttachment(
            Attachment.fromBinaryBytes(
                ScreenshotUtil.takeScreenshot( activityTestRule.getActivity()),
                MediaType.PNG).showDirectly()) ;
    }
}
----

=== Example Project

You can find a complete example project on GitHub: https://github.com/TNG/JGiven/tree/master/example-projects/android
