== Life-Cycle Methods
:sourcedir: ../jgiven-examples/src/test/java/com/tngtech/jgiven/examples

=== Scenario Life-Cycle

The life-cycle of a scenario is as follows.

. An instance for each stage class is created
. The `before()` methods of all scenario rules of all stages are called
. The `@BeforeScenario`-annotated methods of all stages are called
. For each stage:
.. Values are injected into all scenario state fields
.. The `@BeforeStage`-annotated methods of the stage are called
.. The steps of the stage are executed
.. The `@AfterStage`-annotated methods of the stage are called
.. The values of all scenario state fields are extracted.
. The `@AfterScenario`-annotated methods of all stages are called.
. The `after()` methods of all scenario rules of all stages are called.

==== Integration into Test Frameworks' Lifecycles
The relative ordering of JGiven's lifecycle methods to that of the embedding test framework depends on how JGiven is hooked into it. For JUnit4, JGiven's before and after methods are called later than their respective framework counterparts. Especially the `@After` method is executed ahead of an `@AfterScenario` method or an `after()` method of a scenario rule. For JUnit5 and TestNg, JGiven's `before()` method is executed later than the before method and JGiven's `after()` method is executed ahead of the frameworks' counterparts.

JGivens lifecycle is works best with a per-method lifecycle of the test class. For such a model single and parallel execution of scenarios is fully supported. For a per-class lifecycle single-threaded execution is fully supported and parallel execution has been shown to work for Test classes that inherit from scenario classes.


=== @BeforeScenario / @AfterScenario

==== @BeforeScenario

Methods annotated with `@BeforeScenario` are executed before any step of any stage of a scenario.
This is useful for some general scenario setup.
As an example, you could initialize a WebDriver instance for Selenium tests or set up a database connection.
Note that such methods are executed before the injection of values.
Thus, the annotated code must not depend on scenario state fields.

[source,java]
----
include::{sourcedir}/userguide/MyWebDriverUsingStage.java[tags=start,indent=0]
----

==== @AfterScenario

Analogous to `@BeforeScenario` there is the `@AfterScenario` annotation to execute a methods when a scenario has finished.

[source,java]
----
include::{sourcedir}/userguide/MyWebDriverUsingStage.java[tags=middle,indent=0]
----

=== @ScenarioRule

`@BeforeScenario` and `@AfterScenario` methods are often used to set up and tear down some resource.
If you want to reuse such a resource in another stage, you would have to copy these methods into that stage.
To avoid that, JGiven offers a concept similar to JUnit rules.
The idea is to have a separate class that only contains the before and after methods.
This class can then be reused in multiple stages.

A scenario rule class can be any class that provides the methods `before()` and `after()`.
This is compatible with JUnit’s `ExternalResource` class, which means that you can use classes like `TemporaryFolder` from JUnit directly in JGiven.

==== Example

[source,java]
----
include::{sourcedir}/userguide/WebDriverRule.java[tags=noPackage]

include::{sourcedir}/userguide/MyWebDriverUsingStage.java[tags=rule]
}

----

=== @BeforeStage / @AfterStage

==== @BeforeStage

Methods annotated with `@BeforeStage` are executed after injection, but before the first step method is called.
This is useful for setting up code that is required by all or most steps of a stage.

[source,java]
----
@BeforeStage
public void setup() {
  // do something useful to set up the stage
}
----

==== @AfterStage

Analogous to `@BeforeStage` methods, methods can be annotated with `@AfterStage`.
These methods are executed after all steps of a stage have been executed, but before extracting the values of scenario state fields.
Thus, you can prepare state for following stages in an `@AfterStage` method.
A typical use case for this is to apply the builder pattern to build a certain object using step methods and build the final object in an `@AfterStage` method.

==== Example

[source,java]
----
include::{sourcedir}/userguide/MyStage.java[tags=noPackage]
----

==== Repeatable Stage Methods

The `@BeforeStage` and `@AfterStage` methods come with an optional parameter that allows to execute these methods each time you enter or leave the stage, respectively.

[source,java]
----
@BeforeStage(repeatable=true)
void setup(){
    //do something useful several times
}
----

The process of entering or leaving a stage is determined by a change of the active stage class.
Hence, in order for a repeated execution to work, a different stage has had to be executed in between two invocations of the same stage.
Therefore, the following setup only executes the `@BeforeStage` once.

[source,java]
----
class RepeatableStage extends Stage<RepeatableStage>{
    @BeforeStage(repeatable=true)
    void beforeStageMethod(){ /*...*/}

    public void given_method(){/*...*/}

    public void when_method() {/*...*/}
}
class UseRepeatableStage {
    //...
    @Test
    public void test(){
        //@BeforeStage will only be executed before this invocation
        repeatableStage.given().given_method();
        //Still the same stage class, no @BeforeStage execution here
        repeatableStage.when().when_method();
    }
}
----
Likewise, `@AfterStage` methods in such scenarios will only be executed after the last invocation of the stage.


