== Parameterized Scenarios
:sourcedir: ../jgiven-examples/src/test/java/com/tngtech/jgiven/examples

JGiven scenarios can be parameterized. This is very useful for writing data-driven scenarios, where the scenarios itself are the same, but are executed with different example values.

Parameterization of Scenarios works with TestNG and JUnit, we only show it for JUnit. For TestNG it works analogous.

=== JUnit

JGiven supports several different ways to parameterize a JUnit test:

. JUnit’s built-in Parametrized Runner
. https://github.com/TNG/junit-dataprovider[JUnit DataProvider]
. https://github.com/Pragmatists/JUnitParams[JUnitParams]

We use the JUnit Dataprovider in the following.

=== JUnit Dataprovider Runner

https://github.com/TNG/junit-dataprovider[JUnit Dataprovider] provides a JUnit test runner that enables the execution of paramterized test methods. It is similar to the way parameterized tests work in http://testng.org/[TestNG].

==== Example
[source,java]
----
include::{sourcedir}/coffeemachine/ServeCoffeeTest.java[tags=dataprovider]
----
The resulting report will then look as follows:

----
 Coffee is not served

   Given a coffee machine
     And the coffee costs 2 euros
     And there are <coffees> coffees left in the machine
    When I insert <euros> one euro coins
     And I press the coffee button
    Then I should not be served a coffee

  Cases:

   | # | coffees | euros | Status  |
   +---+---------+-------+---------+
   | 1 |       1 |     1 | Success |
   | 2 |       0 |     2 | Success |
   | 3 |       1 |     0 | Success |
----