== Report Generation

=== Plain Text Reports

By default, JGiven outputs plain text reports to the console when executed. To disable plain text reports set the following Java system property:

[source,properties]
----
jgiven.report.text=false
----

=== JSON Reports

By default, JGiven will generate JSON reports into the `jgiven-reports/json` directory. JGiven tries to autodetect when it is executed by the Maven surefire plugin and in that case generates the reports into `target/jgiven-reports/json`. To disable JSON report generation set the following Java system property:

[source,properties]
----
jgiven.report.enabled=false
----

[NOTE]
====
In order to generate HTML or AsciiDoc reports, JSON reports are required.
====

==== Change report directory

If you want to change the `jgiven-reports/json` directory, respectively `target/jgiven-reports/json`, set the following Java system property:

[source,properties]
----
jgiven.report.dir=<targetDir>
----

If JGiven is executed by the Maven surefire plugin, this can be done by the systemPropertyVariables configuration (see: http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html).

[NOTE]
====
In case HTML or AsciiDoc reports are being generated,
the source directory for the JSON reports needs to be set accordingly
(see <<HTML Report>> or <<AsciiDoc Report>> for more).
====

==== Dry Run

There is a dry run option, which just generates a report without actually
executing the code. This might be helpful to generate a test report quickly
without having to wait for the tests to be executed.

[source,properties]
----
jgiven.report.dry-run=true
----

[NOTE]
====
As the tests are not really executed and thus cannot fail,
all tests will be reported as successful.
====

=== HTML Report

To generate an HTML report you have to run the JGiven report generator
with the `html` format option.
The reporter is part of the `jgiven-html5-report` module.
The report generator can be executed on the command line as
follows (assuming that the `jgiven-core` and the `jgiven-html5-report` JAR
and all required dependencies are on the Java CLASSPATH)

[source,console]
----
$ java com.tngtech.jgiven.report.ReportGenerator \
    --format=html \
    [--sourceDir=<jsonreports>] \
    [--targetDir=<targetDir>] \
----

To see the HTML report in action you can have a look at the
https://jgiven.org/jgiven-report/html5/[HTML report of JGiven itself]

=== AsciiDoc Report

To generate an AsciiDoc report you have to run the JGiven report generator with the `asciidoc` format option.
The report generator can be executed on the command line as follows
(assuming that the `jgiven-core` JAR and all required dependencies are on the Java CLASSPATH)


[source,console]
----
$ java com.tngtech.jgiven.report.ReportGenerator \
    --format=asciidoc \
    [--sourceDir=<jsonreports>] \
    [--targetDir=<targetDir>]
----

To see the AsciiDoc report in action you can have a look at the
https://jgiven.org/jgiven-report/asciidoc/[AsciiDoc report of JGiven itself]

=== Maven Plugin

For Maven there exists a plugin that can be used as follows:

[source,xml,subs="verbatim,attributes"]
----
<build>
  <plugins>
    <plugin>
      <groupId>com.tngtech.jgiven</groupId>
      <artifactId>jgiven-maven-plugin</artifactId>
      <version>{version}</version>
      <executions>
        <execution>
          <goals>
            <goal>report</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <format>html</format>
      </configuration>
    </plugin>
 </plugins>
</build>
----

You can add the following configuration options (like the _format_ configuration above) to customize the report.
All of them are optional.

[cols="1,3"]
.Configuration Options for Reports
|===
|Option |Description

|format
|The format of the generated report. Can be _html_, _text_ or _asciidoc_. Default: _html_

|title
|The title of the generated report. Default: _JGiven Report_

|customCssFile
|Custom CSS file to customize the HTML report. Default: _src/test/resources/jgiven/custom.css_

|customJsFile
|Custom JS file to customize the HTML report. Default: _src/test/resources/jgiven/custom.js_

|excludeEmptyScenarios
|Whether or not to exclude empty scenarios, i.e. scenarios without any steps, from the report. Default: _false_

|outputDirectory
|Directory where the reports are generated to. Default: _${project.build.directory}/jgiven-reports/html_

|sourceDirectory
|Directory to read the JSON report files from. Default: _${project.build.directory}/jgiven-reports/json_

|===

Now run:

[source,console]
----
$ mvn verify
----

HTML reports are then generated into the `target/jgiven-reports/html` directory.
Note that the plugin relies on the existence of the JSON output,
so if the property `jgiven.reports.enabled` was set to `false`,
no output will be generated.

Use the following configuration to generate the AsciiDoc report instead of the HTML report.

[source,xml,subs="verbatim,attributes"]
----
<build>
  <plugins>
    <plugin>
      <groupId>com.tngtech.jgiven</groupId>
      <artifactId>jgiven-maven-plugin</artifactId>
      <version>{version}</version>
      <executions>
        <execution>
          <goals>
            <goal>report</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <format>asciidoc</format>
        <outputDirectory>${project.build.directory}/jgiven-reports/asciidoc</outputDirectory>
      </configuration>
    </plugin>
 </plugins>
</build>
----

=== Gradle Plugin

There also exists a plugin for Gradle to make your life easier.
Add the following plugins section to your `build.gradle` file or extend the one you have already accordingly:

[source,gradle,subs="verbatim,attributes"]
----
plugins {
    id "com.tngtech.jgiven.gradle-plugin" version "{version}"
}
----

When using Kotlin, make sure the JGiven Gradle plugin is configured _after_ the `kotlin("jvm")` plugin.

Alternatively you can configure the plugin as follows:

[source,gradle,subs="verbatim,attributes"]
----
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.tngtech.jgiven:jgiven-gradle-plugin:{version}"
    }
}

apply plugin: "com.tngtech.jgiven.gradle-plugin"
----

Now run:

[source,console]
----
$ gradle test jgivenTestReport
----

HTML reports are then generated into the `build/reports/jgiven/test/html/` directory.
Note that the plugin relies on the existence of the JSON output,
so if the property `jgiven.reports.enabled` was set to `false`,
no output will be generated.

If you want that the HTML report is always generated after the tests
have been executed, you can configure the `test` task in your Gradle
configuration file as follows:

[source,gradle]
----
test.finalizedBy jgivenTestReport
----

For additional information about the Gradle plugin refer to
https://plugins.gradle.org/plugin/com.tngtech.jgiven.gradle-plugin

=== Configuration File

JGiven will optionally load a configuration properties file, defaulting to:
`jgiven.properties`. The path to the configuration can be customized with the system property:

----
jgiven.config.path
----

The encoding for the file is assumed to be `UTF-8`, but can be customized with the system property:

----
jgiven.config.charset
----

The following can be defined in the properties file:

[source,properties]
----
jgiven.report.enabled=false
jgiven.report.dir=<targetDir>
jgiven.report.text=false
jgiven.report.text.color=auto
jgiven.report.filterStackTrace=true
jgiven.report.dry-run=false
----

Configuration defined via Java system properties will take precedence over values in the configuration file.
