== Report Generation

=== Plain Text Reports

By default JGiven outputs plain text reports to the console when executed. To disable plain text reports set the following Java system property:

[source,java]
----
jgiven.report.text=false
----

=== JSON Reports

By default JGiven will generate JSON reports into the `jgiven-reports/json` directory. JGiven tries to autodetect when it is executed by the Maven surefire plugin and in that case generates the reports into `target/jgiven-reports/json`. To disable JSON report generation set the following Java system property:

[source,java]
----
jgiven.report.enabled=false
----

Note that in order to generate HTML reports, JSON reports are required.

=== HTML Report

To generate an HTML report you have to run the JGiven report generator
with the `html` format option.
The reporter is part of the `jgiven-html5-report` module.
The report generator can be executed on the command line as
follows (assuming that the `jgiven-core` and the `jgiven-html5-report` JAR
and all required dependencies are on the Java CLASSPATH)


[source,bash]
----
java com.tngtech.jgiven.report.ReportGenerator \
  --format=html \
  [--sourceDir=<jsonreports>] \
  [--targetDir=<targetDir>] \
----

To see the HTML report in action you can have a look at the
http://jgiven.org/jgiven-report/html5/[HTML report of JGiven itself]

==== Maven

For Maven there exists a plugin that can be used as follows:

[source,xml,subs="verbatim,attributes"]
----
<build>
  <plugins>
    <plugin>
      <groupId>com.tngtech.jgiven</groupId>
      <artifactId>jgiven-maven-plugin</artifactId>
      <version>{version}</version>
      <executions>
        <execution>
          <goals>
            <goal>report</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <format>html</format>
      </configuration>
    </plugin>
 </plugins>
</build>
----

You can add the following configuration options (like the _format_ configuration above) to customize the report.
All of them are optional.

[cols="1,3"]
.Configuration Options for Reports
|===
|Option |Description

|format
|The format of the generated report. Can be _html_ or _text_. Default: _html_

|title
|The title of the generated report. Default: _JGiven Report_

|customCssFile
|Custom CSS file to customize the HTML report. Default: _src/test/resources/jgiven/custom.css_

|customJsFile
|Custom JS file to customize the HTML report. Default: _src/test/resources/jgiven/custom.js_

|excludeEmptyScenarios
|Whether or not to exclude empty scenarios, i.e. scenarios without any steps, from the report. Default: _false_

|outputDirectory
|Directory where the reports are generated to. Default: _${project.build.directory}/jgiven-reports/html_

|sourceDirectory
|Directory to read the JSON report files from. Default: _${project.build.directory}/jgiven-reports/json_

|===

Now run:

[source,bash]
----
$ mvn verify
----

HTML reports are then generated into the `target/jgiven-reports/html` directory.

==== Gradle

There also exists a plugin for Gradle to make you life easier.
Add the following plugins section to your `build.gradle` file or extend the one you have already accordingly:

[source,gradle,subs="verbatim,attributes"]
----
plugins {
    id "com.tngtech.jgiven.gradle-plugin" version "{version}"
}
----

Alternatively you can configure the plugin as follows:

[source,gradle,subs="verbatim,attributes"]
----
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.tngtech.jgiven:jgiven-gradle-plugin:{version}"
    }
}

apply plugin: "com.tngtech.jgiven.gradle-plugin"
----

Now run:

[source,bash]
----
$ gradle test jgivenTestReport
----

HTML reports are then generated into the `build/reports/jgiven/test/html/` directory.

If you want that the HTML report is always generated after the tests
have been executed, you can configure the `test` task in your Gradle
configuration file as follows:

[source,gradle]
----
test.finalizedBy jgivenTestReport
----

For additional information about the Gradle plugin refer to
https://plugins.gradle.org/plugin/com.tngtech.jgiven.gradle-plugin
