== Spring
:javadocurl: http://static.javadoc.io/com.tngtech.jgiven/jgiven-spring/{version}/com/tngtech/jgiven/integration/spring

Only two steps are required to use JGiven together with Spring or Spring-Boot. First,
<<Install Dependency, install the right dependency>>. Second,
<<Configure Spring, make your Spring Test Configuration aware of JGiven>>.

If you're using JUnit, however, you need to inherit from a
<<Use JGiven in JUnit-based Spring Tests, spring scenario class>>. Finally, if you want your test stages to act as
Spring Beans, you need to add a <<Stages as Spring Beans, special annotation>> to them.

=== Install Dependency
Spring support is provided by the `jgiven-spring-junit4` and the `jgiven-spring-junit5` dependencies,
depending on which JUnit version you are using. JUnit 5 is only supported with version 5 of Spring.

==== Maven

[source,maven,subs="verbatim,attributes"]
----
<dependency>
   <groupId>com.tngtech.jgiven</groupId>
   <artifactId>jgiven-spring-junit5</artifactId>
   <version>{version}</version>
   <scope>test</scope>
</dependency>
----

==== Gradle

[source,gradle,subs="verbatim,attributes"]
----
dependencies {
    testImplementation("com.tngtech.jgiven:jgiven-spring-junit5:{version}")
}
----

=== Configure Spring

In order to enable the JGiven Spring integration you have to tell Spring about the
existence of JGiven.

==== Annotation-Based
If you are using the annotation-based configuration of Spring you can annotate your Spring
Test Configuration with the link:{javadocurl}/EnableJGiven.html[`@EnableJGiven`] annotation.
This is all you have to do to configure Spring for JGiven.

===== Example

[source,java]
----
@EnableJGiven
@Configuration
@ComponentScan("the project")
public class MySpringTestConfig {
   //...
}
----

==== XML-Based
You can also configure JGiven with XML by adding the `jgiven:annotation-driven` tag to your
Spring XML config.

===== Example
[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context"
    xmlns:jgiven="http://jgiven.org/jgiven-spring"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
                        http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd
                        http://jgiven.org/jgiven-spring http://jgiven.org/schemas/jgiven-spring.xsd">

  <jgiven:annotation-driven/>

</beans>
----

=== Use JGiven in JUnit-based Spring Tests
==== JUnit 4
In order to use JGiven in JUnit 4 based Spring tests, you should inherit from:

    - `SpringRuleScenarioTest`
    - `SimpleSpringRuleScenarioTest`

These base classes contain all the methods and JUnit rules necessary to run JGiven with Spring.

==== JUnit 5
To use JGiven in JUnit 5 based Spring Tests you should inherit from one of the provided tests classes:

   - `SpringScenarioTest`
   - `SimpleSpringScenarioTest`

Both classes contain all the annotations and methods necessary to run JGiven with Spring. The `SimpleSpringScenarioTest` allows to have all stages in a single stage class, while the `SpringScenarioTest` allows to have a class for each stage.

===== Example

[source,java]
----
@SpringBootTest(classes={MySpringTestConfig.class})
class MySpringBootApplicationTest extends SimpleSpringScenarioTest<MyStage> {
   //...
}
----
If you cannot or don't want to inherit from these classes, you
can copy the content of these classes (one method) into one of your test base classes.

=== Stages as Spring Beans

In order to treat JGiven stages as Spring beans, e.g. if you want to inject
 other Spring beans into your stages, you have to annotate
the stage class with the link:{javadocurl}/JGivenStage.html[`@JGivenStage`] annotation.

==== Example

[source, java]
----
@JGivenStage
public class MyStage {

   @Autowired
   MyService myService;
}
----

=== Example Project

You find a complete example project, a SpringBoot webapp tested with JGiven, on GitHub: https://github.com/TNG/JGiven/tree/master/example-projects/spring-boot
