== Spring
:javadocurl: http://static.javadoc.io/com.tngtech.jgiven/jgiven-spring/{version}/com/tngtech/jgiven/integration/spring

=== Install Dependency
Spring support is provided by the `jgiven-spring-junit4` and the `jgiven-spring-junit5` dependencies, depending
on which JUnit version you are using. JUnit 5 is only supported with version 5 of Spring.

==== Maven

[source,maven,subs="verbatim,attributes"]
----
<dependency>
   <groupId>com.tngtech.jgiven</groupId>
   <artifactId>jgiven-spring-junit5</artifactId>
   <version>{version}</version>
   <scope>test</scope>
</dependency>
----

==== Gradle

[source,gradle,subs="verbatim,attributes"]
----
dependencies {
    testCompile("com.tngtech.jgiven:jgiven-spring-junit5:{version}")
}
----

=== Configure Spring

In order to enable the JGiven Spring integration you have to tell Spring about the
existence of JGiven.

==== Annotation-Based
If you are using the annotation-based configuration of Spring you can annotate your Spring
configuration with the link:{javadocurl}/EnableJGiven.html[`@EnableJGiven`] annotation.
This is all you have to do to configure Spring for JGiven.

===== Example

[source,java]
----
@EnableJGiven
@Configuration
public class MySpringConfig {
   ...
}
----

==== XML-Based
You can also configure JGiven with XML by adding the `jgiven:annotation-driven` tag to your
Spring XML config.

===== Example
[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context"
    xmlns:jgiven="http://jgiven.org/jgiven-spring"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
                        http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd
                        http://jgiven.org/jgiven-spring http://jgiven.org/schemas/jgiven-spring.xsd">

  <jgiven:annotation-driven/>

</beans>
----

=== Use JGiven in JUnit-based Spring Tests

To now use JGiven in JUnit-based Spring Tests you should inherit from one of the provided tests classes:

   - `SpringScenarioTest`
   - `SpringRuleScenarioTest`
   - `SimpleSpringScenarioTest`
   - `SimpleSpringRuleScenarioTest`

The test classes with `SpringRule` tests already include the Spring JUnit rules, thus you need to add these
rules to your test class and you also don't have to specify the Spring JUnit runner.

If you cannot or don't want to inherit from these classes, you
can copy the content of these classes (one method) into one of your test base classes.

=== Stages as Spring Beans

In order to treat JGiven stages as Spring beans, e.g. if you want to inject
 other Spring beans into your stages, you have to annotate
the stage class with the link:{javadocurl}/JGivenStage.html[`@JGivenStage`] annotation.

==== Example

[source, java]
----
@JGivenStage
public class MyStage {

   @Autowired
   MyService myService;
}
----

=== Example Project

You find a complete example project on GitHub: https://github.com/TNG/JGiven/tree/master/example-projects/spring-boot
