== Stages and State Sharing
:sourcedir: ../jgiven-examples/src/test/java/com/tngtech/jgiven/examples


A JGiven scenario consists of multiple stages. Typically there is a stage for each phase of a scenario: a given stage, a when stage and a then stage, however, it is also possible to just use one stage or use arbitrary many stages. A stage is implemented by a stage class that contains methods representing the steps that can be used in the scenario. The big advantage of this modular concept is that stages can be easily reused by different scenarios.

=== Step Methods

A stage class contains multiple step methods that can be called in a scenario and that will appear in the report. Every non-private, non-final, non-static method of a stage class can be used as a step method. There are no further requirements. In particular, no annotations are needed. Step methods should return the this reference so that chaining of calls is possible. In addition, a step method should be written in snake_case so that JGiven knows the correct casing of each word of the step.

The following code shows a valid step method of the `WhenCook` stage:


[source,java]
----
include::{sourcedir}/pancakes/test/steps/WhenCook.java[tags=cookManglesDough,indent=0]
----
JGiven removes the underlines so the step will appear as _the cook mangles everything to a dough_ in the report.

=== Overriding the Default Reporting

Sometimes it is necessary to override the default way of the step reporting. For example, if you want to use special characters that are not allowed in Java methods names, such as `(`, `+`, or `%`. You can then use the `@As` annotation to specify what JGiven should put into the report.

For example, if you define the following step method:

[source,java]
----
include::{sourcedir}/userguide/WhenCalculator.java[tags=method,indent=0]
----
The step will appear as `10 % are added` in the report, when invoked with `10`.

=== Completely Hide Steps

Steps can be completely hidden from the report by using the http://jgiven.org/javadoc/com/tngtech/jgiven/annotation/Hidden.html[`@Hidden`] annotation. This is sometimes useful if you need a technical method call within a scenario, which should not appear in the report.

For example:



[source,java]
----
include::{sourcedir}/userguide/RocketMethods.java[tags=hiddenRocket,indent=0]
----
Note that it is useful to write hidden methods in `CamelCase` to make it immediately visible in the scenario that these methods will not appear in the report.

=== Extended Descriptions

Steps can get an extended description with the http://jgiven.org/javadoc/com/tngtech/jgiven/annotation/ExtendedDescription.html[`@ExtendedDescription`] annotation. You can use this to give additional information about the step to the reader of the report. In the HTML report this information is shown in a tooltip.

Example:

[source,java]
----
include::{sourcedir}/userguide/RocketMethods.java[tags=rocketDesc,indent=0]
----

=== Intro Words

If the predefined introductionary words in the http://jgiven.org/javadoc/com/tngtech/jgiven/Stage.html[`Stage`] class are not enough for you and you want to define additional ones you can use the http://jgiven.org/javadoc/com/tngtech/jgiven/annotation/IntroWord.html[`@IntroWord`] annotation on a step method.

Example:

[source,java]
----
@IntroWord
public SELF however() {
   return self();
}
----

Note that you can combine `@IntroWord` with the `@As` annotation. To define a `,` as an introductionary word, for example, you can define:



[source,java]
----
@IntroWord
@As(",")
public SELF comma() {
   return self();
}
----

=== State Sharing

Very often it is necessary to share state between steps.
As long as the steps are implemented in the same Stage class you can just use the fields of the Stage class.
But what can you do if your steps are defined in different Stage classes?
In this case you just define the same field in both Stage classes.
Once in the Stage class that _provides_ the value of the field and once in the Stage class that _needs_ the value
of the field.
Both fields also have to be annotated with the special annotation `@ScenarioState` to tell JGiven that
this field will be used for state sharing between stages.
The values of these fields are shared between all stages that have the same field.
For example, to be able to access the value of the ingredients field of the GivenIngredients stage in the `WhenCook` stage one has to annotate that field accordingly:


[source,java]
----
include::{sourcedir}/pancakes/test/steps/GivenIngredients.java[]

----



[source,java]
----
include::{sourcedir}/pancakes/test/steps/WhenCook.java[tags=state]
----

Instead of the `@ScenarioState` annotation one can also use `@ExpectedScenarioState` and `@ProvidedScenarioState` to indicate whether the state is expected by the stage or provided by the stage.
These function in exactly the same way as `@ScenarioState` but are more descriptive about what the code is doing.

==== Type vs. Name Resolution

Scenario state fields are by default resolved by its type.
That is, you can only have one field of the same type as a scenario field.
Exceptions are types from the packages `java.lang.\*` and `java.util.*` which are resolved by the name of the field.

To change the resolution strategy you can use the `resolution` parameter of the `@ScenarioState` annotations. For example, to use name instead of type resolution you can write

`@ScenarioState(resolution = Resolution.NAME)`.

==== Value Validation
By default, JGiven will not validate whether the value of a field of a stage that expects a value,
was actually provided by a previous stage.
The reason for this is that typically not all fields are always required for all steps.
There might be scenarios where only a part of the fields are really necessary for the steps of the scenario.
However, sometimes you know that a certain field value is needed for *all* steps of a stage.
In this case you can set the `required` attribute of the `@ScenarioState` or `@ExpectedScenarioState` annotation to `true`.
JGiven will then validate that a previous stage had provided the value and will throw an exception otherwise.

=== Having More Than 3 Stages

In many cases three stages are typically enough to write a scenario. However, sometimes more than three are required. JGiven provides two mechanism for that: stage injection and dynamic adding of stages.

==== Stage Injection

Additional stages can be injected into a test class by declaring a field with the additional stage and annotate it with `@ScenarioStage`.

===== Example

In the following example we inject an additional stage `GivenAdditionalState` into the test class and use it in the test.


[source,java]
----
include::{sourcedir}/userguide/MyInjectedJGivenTest.java[tags=noPackage]
----

Note that the field access will not be visible in the report. Thus the resulting report will look as follows:

--
Scenario: something should happen

  Given some state
    And some additional state
   When some action
   Then some outcome
--

Also note that you should not forget to first invoke an intro method, like `and()` or `given()` on the injected stage before calling the step method.

==== Dynamic Adding of Stages

The disadvantage of injecting a stage into a test class is that this stage will be used for all tests of that class. This might result in an overhead if the stage contains `@BeforeScenario` or `@AfterScenario` methods, because these methods will also be executed in the injected stages. If an additional stage is only required for a single test method you should instead dynamically add that stage to the scenario by using the `addStage` method.

===== Example


[source,java]
----
include::{sourcedir}/userguide/MyDynamicallyAddedTest.java[tags=noPackage]
----

=== Subclassing of Stages

In practice, it often makes sense to have a hierarchy of stage classes. Your top stage class can implement common steps that you require very often, while subclasses implement more specialized steps.

One problem with subclassing stage classes is to keep the fluent interface intact. Let’s have an example:


[source,java]
----
include::{sourcedir}/subclassing/GivenCommonSteps.java[tags=noPackage]
----
Now assume that we create a subclass of `GivenCommonSteps`:



[source,java]
----
include::{sourcedir}/subclassing/GivenSpecialSteps.java[tags=noPackage]
----
If you now want to use the `GivenSpecialSteps` stage, you will get problems when you want to chain multiple step methods:



[source,java]
----
include::{sourcedir}/subclassing/CommonStagesTest.java[tags=onlyMethod,indent=0]
----

This code will not compile, because `my_common_step()` returns `GivenCommonSteps` and not `GivenSpecialSteps`.

Luckily this problem can be fixed with generic types. First you have to change the `GivenCommonSteps` class as follows:



[source,java]
----
include::{sourcedir}/subclassing/GivenCommonStepsFixed.java[tags=noPackage]
----
That is, you give `GivenCommonSteps` a type parameter `SELF` that can be specialized by subclasses. This type is also used as return type for `my_common_step()`. Instead of returning `this` you return `self()`, which is implemented in the `Stage` class.

Now your subclass must be change as well:



[source,java]
----
include::{sourcedir}/subclassing/GivenSpecialStepsFixed.java[tags=noPackage]
----